import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Ads by festival</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <Header /> */}

            <main>
                <div id="home">
                    <section className="container">
                        <div className="enunciados">
                            <p>Promociona tu marca <br />y consigue <span>más ventas</span></p>
                            <p>Anuncia en la red de portales de entretenimiento en <br />español con mayor audiencia de la región.</p>
                            <p>Regístrate y empieza a anunciar</p>
                            <div className="registro">
                                <input type="text" placeholder="Correo electrónico" />
                                <button>Comienza ahora</button>
                            </div>
                        </div>
                        <div>
                            <img src="https://picsum.photos/400/300" />
                        </div>
                    </section>
                </div>

                <div id="alcance">
                    <div className="porque-anunciar">
                        <p>¿Por qué anunciar en festival?</p>
                        <article>
                            <div>
                                <div>
                                    1
                                </div>
                                <div>
                                    <p>Anuncios de alto impacto<br /><span>Formatos creativos de gran impacto en los medios más importantes.</span></p>
                                </div>
                            </div>
                            <div>
                                <div>
                                    2
                                </div>
                                <div>
                                    <p>Encuentra a tu audiencia<br /><span>Usa nuestro segmentación para llegar a tu público objetivo.</span></p>
                                </div>
                            </div>
                            <div>
                                <div>
                                    3
                                </div>
                                <div>
                                    <p>Mide tus resultados<br /><span>Obtén feedback automatizado sobre la respuestas de tu audiencia.</span></p>
                                </div>
                            </div>
                        </article>
                    </div>
                    <div className="alcance">
                        <div>
                            <p>Llega a más clientes con festivad.io</p>
                            <p>Festivad ayuda a negocios de todos los tamaños a conectar con audiencias potenciales mientras consumen el contenido que aman. A través de nuestra plataforma  podrás mostrar anuncios de texto, imagen o video y formatos especiales a millones de personas en minutos.</p>
                        </div>
                        <div>
                            <div>
                                <p>10 M</p>
                                <p>Más de <span>10 millones de personas</span> visitan y consumen los contenidosde nuestros socios todos los meses.</p>
                            </div>
                            <div>
                                <p>55 %</p>
                                <p>Más de la mitad de los usuarios a actuar publicidad no invasiva relacionada a sus contenidos de interés</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="detalles">
                    <section>
                        <div>
                            <img src="https://picsum.photos/300/300" />
                        </div>
                        <div>
                            <p>Muéstrate al mundo sin importar tu presupuesto</p>
                            <p>Sin subastas de espacios ni costos variables. Nuestros paquetes te permiten anunciar en todo el mundo desde $50.</p>
                        </div>
                    </section>

                    <section>
                        <div>
                            <img src="https://picsum.photos/300/300" />
                        </div>
                        <div>
                            <p>Muéstrate al mundo sin importar tu presupuesto</p>
                            <p>Sin subastas de espacios ni costos variables. Nuestros paquetes te permiten anunciar en todo el mundo desde $50.</p>
                        </div>
                    </section>

                    <section>
                        <div>
                            <img src="https://picsum.photos/300/300" />
                        </div>
                        <div>
                            <p>Muéstrate al mundo sin importar tu presupuesto</p>
                            <p>Sin subastas de espacios ni costos variables. Nuestros paquetes te permiten anunciar en todo el mundo desde $50.</p>
                        </div>
                    </section>
                </div>
            </main>

            {/* <Footer /> */}
        </div>
    )
}

export default Home
