import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Ads by festival</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <Header /> */}

            <main>
                <div id="home">
                    <section className="container">
                        <div className="enunciados">
                            <p>Promociona tu marca <br />y consigue <span>más ventas</span></p>
                            <p>Anuncia en la red de portales de entretenimiento en <br />español con mayor audiencia de la región.</p>
                            <p>Regístrate y empieza a anunciar</p>
                            <div className="registro">
                                <input type="text" placeholder="Correo electrónico" />
                                <button>Comienza ahora</button>
                            </div>
                        </div>
                        <div>
                            <img src="https://picsum.photos/400/300" />
                        </div>
                    </section>
                </div>

                <div id="alcance">
                    <div className="porque-anunciar">
                        <p>¿Por qué anunciar en festival?</p>
                        <article>
                            <div>
                                <div>
                                    1
                                </div>
                                <div>
                                    {/* <p><span>Anuncios de alto impacto</span><br />Formatos creativos de gran impacto en los medios más importantes.</p> */}
                                </div>
                            </div>
                            <div>
                                <div>
                                    2
                                </div>
                                <div></div>
                            </div>
                            <div>
                                <div>
                                    3
                                </div>
                                <div></div>
                            </div>
                        </article>
                    </div>
                </div>
            </main>

            {/* <Footer /> */}
        </div>
    )
}

export default Home
